CCC = g++
LEX = flex
YACC = bison
CFLAGS = -Wall --coverage -g
LEXFLAGS = -Wno-unused

OBJS = main.o parse.tab.o lex.yy.o

all: run

test: run
	python runtests.py


report:
	lcov --capture --directory . --output-file cov.info
	genhtml cov.info --output-directory report
	echo Coverage report in report/index.html

run: $(OBJS)
	$(CCC) $(CFLAGS) -o run $(OBJS)

main.o: main.cpp
	$(CCC) $(CFLAGS) -c main.cpp

parse.tab.c: parse.y
	$(YACC) -d -v parse.y

parse.tab.o: parse.tab.c
	$(CCC) $(CFLAGS) -c parse.tab.c

lex.yy.c: scan.l parse.tab.o
	$(LEX) scan.l

lex.yy.o: lex.yy.c
	$(CCC) $(CFLAGS) $(LEXFLAGS) -c lex.yy.c
	
clean:
	rm -f run *.o parse.tab.c lex.yy.c
	rm -f parse.tab.h
	rm -f graph.gv graph.png
	rm -f *.gcda *.gcno *.bb *.bbg *.da *.gcov
	rm -rf report cov.info
